data_folder: "/isic2018/data"
raw_data_folder: "/isic2018/raw_data"
task: isic


dataset:
  train: /isic2018/data/fedmu
  val: /isic2018/data/fedmu/val.csv
  test: /isic2018/data/fedmu/test.csv
  forgotten: /isic2018/data/fedmu/forgotten.csv
  remembered: /isic2018/data/fedmu/remembered.csv
  resize:
    height: 224
    width: 224
  mean: [0.763,0.546,0.570]
  std: [0.141,0.153,0.170]
  seed: 42

model:
  model_path: /isic2018/data/fedmu/checkpoints/poisoned_origin/best_val_auc_avg.pth
  torch_room: /home/user/fedmu/models
  pretrained: True
  drop_rate: 0
  mode: U-MultiClass
  num_classes: 7

eval:
  level: image
  metric: val/auc_avg
  
train:
  device: null
  gpu_exclude: [3]
  eval_interval: 500
  test_interval: 1000
  test_start: 10000
  use_CMSL: False
  checkpoint_dir: /isic2018/data/fedmu/checkpoints/
  resume_path: null
  batch_size: 64
  num_workers: 8
  max_epoch: null
  max_iter: 20000
  optimizer: 
    lr: 1.0e-4
    beta1: 0.9
    beta2: 0.9999
    weight_decay: 5.0e-4
  lr_scheduler:
    factor: 0.1
    patience: 2
    min_lr: 1.0e-7

test: 
  save_as_csv: True
  target_dir: /isic2018/data/fedmu/predicted

wandb:
  key: ""
  project: "fedmu_isic2018"
  run_name: "fedavg"

fl:
  rounds: 20
  unlearn:
    low_freq: 0.7
    ct_lambda: 0.05
    unlearn_iter: 100
    fusion_interval: 10
    optimizer: 
      lr: 1.0e-5
      beta1: 0.9
      beta2: 0.9999
      weight_decay: 5.0e-4
    lr_scheduler:
      factor: 0.1
      patience: 2
      min_lr: 1.0e-7
  test_start_round: 0
  eval_start_round: 0
  save_start_round: 110
  local_iter: 20
  wandb_global: False
  num_clients: 5

hooks:
  wandb: False
